default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

LearnFromMocapBrain:
    normalize: true
    num_epoch: 3
    beta: 0.01
    time_horizon: 100
    max_steps: 2e6
    batch_size: 2048
    buffer_size: 10240
    # buffer_size: 20480
    summary_freq: 1000
    num_layers: 2
    hidden_units: 512

TrainerBrain:
    # use_recurrent: true
    # sequence_length: 64
    normalize: true
    num_layers: 2
    hidden_units: 64
    # memory_size: 256
    max_steps: 1e6
